apiVersion: v1
kind: Namespace
metadata:
  name: sno1-cluster2
  labels:
    # Lets the hub back up and restore this site definition.
    cluster.open-cluster-management.io/backup: cluster-activation
